import { FmeaWorksheet, UserProfile, PeriodicReport, HighRiskAlert } from '@/types/fmea';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-hamid-rafiyan',
    name: 'حمید رفیعیان',
    role: 'hse_manager',
    roleTitle: 'مسئول واحد ایمنی و بهداشت (HSE Manager)',
    department: 'مدیریت ایمنی، بهداشت و محیط‌زیست',
    email: 'rafiyanhamid1989@gmail.com',
    phone: '09120000001',
  },
  {
    id: 'user-saeed-shafiei',
    name: 'سعید شفیعی',
    role: 'hse_officer',
    roleTitle: 'افسر ایمنی و بهداشت حرفه‌ای',
    department: 'واحد ایمنی و بهداشت',
    email: 'shafiei.hse@factory.ir',
    phone: '09120000002',
  },
  {
    id: 'user-mohammad-mounesan',
    name: 'محمد مونسان',
    role: 'hse_officer',
    roleTitle: 'افسر ایمنی و بهداشت حرفه‌ای',
    department: 'واحد ایمنی و بهداشت',
    email: 'mounesan.hse@factory.ir',
    phone: '09120000003',
  },
  {
    id: 'user-mehdi-ahmadi',
    name: 'مهدی احمدی',
    role: 'hse_officer',
    roleTitle: 'افسر ایمنی و بهداشت حرفه‌ای',
    department: 'واحد ایمنی و بهداشت',
    email: 'ahmadi.hse@factory.ir',
    phone: '09120000004',
  },
  {
    id: 'user-mehdi-noori',
    name: 'مهندس مهدی نوری',
    role: 'supervisor',
    roleTitle: 'مسئول واحد PM (نگهداری و تعمیرات پیشگیرانه)',
    department: 'واحد نگهداری و تعمیرات پیشگیرانه (PM)',
    email: 'noori.pm@factory.ir',
    phone: '09120000005',
  },
  {
    id: 'user-adel-moradi',
    name: 'عادل مرادی',
    role: 'supervisor',
    roleTitle: 'مسئول واحد تعمیرات',
    department: 'واحد تعمیرات و خدمات فنی',
    email: 'moradi.repair@factory.ir',
    phone: '09120000006',
  },
];

export const INITIAL_WORKSHEETS: FmeaWorksheet[] = [
  {
    id: 'ws-navard-sard-1404',
    workshopName: 'نوردسرد',
    executionDate: '1404/07/15',
    reviewPeriod: 'سه ماهه',
    teamMembers: ['محمد مونسان', 'سعید شفیعی', 'مهدی احمدی', 'رحمت ترحمی'],
    teamApproved: true,
    teamApprovedDate: '1404/07/16',
    hseManagerApproved: true,
    hseManagerApprovedDate: '1404/07/18',
    hseManagerName: 'حمید رفیعیان',
    status: 'approved',
    notes: 'ارزیابی ریسک فرآیند تعیین ضخامت ورق فولادی و برشکاری کارگاه نورد سرد بر اساس استاندارد FMEA',
    hazards: [
      {
        id: 'h-1',
        rowNumber: 1,
        activity: 'تعیین ضخامت ورق فولادی',
        potentialHazard: 'برخورد ورق به اپراتور',
        consequence: 'جراحت شدید، فوت',
        rootCauses: 'سرعت بالای دستگاه، عدم وجود حریم حفاظتی، انحراف ورق در خروجی رول‌گیر',
        severity1: 10,
        occurrence1: 5,
        detection1: 4,
        rpn1: 200,
        judgment1: 'M',
        existingControls: 'آموزش مقدماتی، نصب تابلو هشدار سرعت',
        proposedControls: 'کنترل سرعت دستگاه - طراحی و ساخت مناسب حفاظ - ساخت اتاقک اپراتوری مجهز به شیشه ضدضربه',
        correctiveAction: {
          id: 'ca-1',
          title: 'ساخت و نصب اتاقک اپراتوری ایزوله و سیستم کنترل سرعت هیدرولیک',
          description: '۱. طراحی و نصب اتاقک عایق شیشه‌ای ضد ضربه برای اپراتور اندازه گیری ۲. نصب درایو اینورتر کنترل هوشمند سرعت رول‌بازکن ۳. تدوین دستورالعمل ایمنی کار با رول‌گیر',
          responsiblePerson: '',
          department: 'واحد تعمیرات و PM',
          targetDate: '1405/02/30',
          completedDate: '1405/02/20',
          status: 'completed',
          estimatedCost: '۴۵,۰۰۰,۰۰۰ تومان',
          effectivenessReview: 'کاهش شدید احتمال پرتاب و اصابت ورق با اپراتور به دلیل قرارگیری در اتاقک محافظ',
          isApprovedByHSE: true,
        },
        severity2: 6,
        occurrence2: 3,
        detection2: 5,
        rpn2: 90,
        judgment2: 'L',
        tags: ['مکانیکی', 'برخورد', 'بحرانی'],
        createdAt: '1404/07/15',
        updatedAt: '1404/08/22',
      },
      {
        id: 'h-2',
        rowNumber: 2,
        activity: 'تعیین ضخامت ورق فولادی',
        potentialHazard: 'برخورد دست با گیوتین',
        consequence: 'قطع عضو - جراحت شدید',
        rootCauses: 'نداشتن سنسور قطع کن، عدم تمرکز، ورود دست به حریم تیغه برش حین تنظیم',
        severity1: 8,
        occurrence1: 6,
        detection1: 3,
        rpn1: 144,
        judgment1: 'M',
        existingControls: 'کلید اضطراری دستی (پدالی)',
        proposedControls: 'نصب سنسور قطع کن نوری (پرده نوری فوتوالکتریک) - آموزش‌های لازم کار با گیوتین',
        correctiveAction: {
          id: 'ca-2',
          title: 'خرید و تجهیز پرده نوری ایمنی Light Curtain روی دهانه گیوتین',
          description: '۱. خرید سنسور پرده نوری تیپ ۴ استانداردی و نصب در فاصله مطمئن از تیغه ۲. اینترلاک سنسور با مدار هیدرولیک استپ اضطراری ۳. برگزاری دوره آموزشی اپراتورها و ثبت آزمون',
          responsiblePerson: '',
          department: 'ایمنی و تعمیرات',
          targetDate: '1405/03/15',
          completedDate: '1405/03/10',
          status: 'completed',
          estimatedCost: '۲۸,۰۰۰,۰۰۰ تومان',
          effectivenessReview: 'در صورت ورود دست بلافاصله تیغه متوقف شده و خطای حرکت صادر می‌شود.',
          isApprovedByHSE: true,
        },
        severity2: 8,
        occurrence2: 4,
        detection2: 4,
        rpn2: 128,
        judgment2: 'M',
        tags: ['برشکاری', 'گیوتین', 'قطع عضو'],
        createdAt: '1404/07/15',
        updatedAt: '1404/08/12',
      },
      {
        id: 'h-3',
        rowNumber: 3,
        activity: 'تعیین ضخامت ورق فولادی',
        potentialHazard: 'سروصدا و نویز صوت بالای ۸۵ دسی‌بل',
        consequence: 'افت شنوایی حسی-عصبی دائمی، سردرد، کاهش تمرکز',
        rootCauses: 'سروصدای ناشی از دستگاه، برخورد تسمه‌ها و زنجیرهای انتقال، و عدم استفاده از گوشی حفاظتی',
        severity1: 8,
        occurrence1: 7,
        detection1: 3,
        rpn1: 168,
        judgment1: 'M',
        existingControls: 'توزیع عمومی ایرپلاگ معمولی',
        proposedControls: 'در اندازه‌گیری عوامل زیان‌آور مشخص می‌شود - استفاده از گوشی‌های حفاظتی مناسب (ایرموف استاندارد) و سایلنسر پنوماتیک',
        correctiveAction: {
          id: 'ca-3',
          title: 'اجرای برنامه پایش دزیمتری صدا و تجهیز به ایرماف ارگونومیک ۳M',
          description: '۱. اندازه‌گیری تراز فشار صوت صوت‌سنجی توسط شرکت معتمد بهداشت کار ۲. نصب صداخفه‌کن روی اگزوزهای پنوماتیک ۳. توزیع و اجبار استفاده از ایرماف کلاس A با NRR بالای ۲۸ دسی‌بل',
          responsiblePerson: '',
          department: 'واحد ایمنی و بهداشت',
          targetDate: '1405/04/01',
          status: 'in_progress',
          estimatedCost: '۱۲,۰۰۰,۰۰۰ تومان',
          effectivenessReview: 'تراز صوتی موثر در گوش اپراتور به زیر ۷۵ دسی‌بل کاهش خواهد یافت.',
          isApprovedByHSE: true,
        },
        severity2: 7,
        occurrence2: 4,
        detection2: 3,
        rpn2: 84,
        judgment2: 'L',
        tags: ['فیزیکی', 'صدا', 'عوامل زیان‌آور'],
        createdAt: '1404/07/15',
        updatedAt: '1404/07/20',
      },
      {
        id: 'h-4',
        rowNumber: 4,
        activity: 'تعیین ضخامت ورق فولادی',
        potentialHazard: 'لیز خوردن، لغزش و سقوط هم‌تراز',
        consequence: 'ضرب دیدگی، کوفتگی، شکستگی دست و پا',
        rootCauses: 'ریختن مواد آب صابون و روغن خنک‌کننده روی زمین - عدم نظافت به موقع و فقدان حوضچه جمع‌آوری',
        severity1: 6,
        occurrence1: 3,
        detection1: 5,
        rpn1: 90,
        judgment1: 'L',
        existingControls: 'نظافت دستی روزانه در پایان شیفت',
        proposedControls: 'اصلاح شیب‌بندی کف، نصب گریتینگ جمع‌آوری مایعات، کفش ضدلغزش ایمنی، چک‌لیست تمیزکاری مستمر',
        correctiveAction: {
          id: 'ca-4',
          title: 'نصب گریتینگ گالوانیزه و سینی درین روغن و تامین کفش‌های استاندارد SRC',
          description: '۱. احداث کانال آبراه و سینی درین در زیر رول‌گیر و پمپ امولسیون ۲. الزام کفش‌های پنجه فولادی با زیره ضد لغزش SRC پلی‌یورتان ۳. قرار دادن پد جاذب روغن در محل‌های مستعد',
          responsiblePerson: '',
          department: 'ایمنی و تعمیرات',
          targetDate: '1405/03/20',
          completedDate: '1405/03/18',
          status: 'completed',
          estimatedCost: '۱۵,۰۰۰,۰۰۰ تومان',
          effectivenessReview: 'کف سالن کاملا خشک مانده و هیچ حادثه لغزشی در ۳۰ روز اخیر گزارش نشده است.',
          isApprovedByHSE: true,
        },
        severity2: 5,
        occurrence2: 2,
        detection2: 4,
        rpn2: 40,
        judgment2: 'L',
        tags: ['ارگونومی', 'لغزش', 'نظافت ۵S'],
        createdAt: '1404/07/15',
        updatedAt: '1404/08/18',
      },
      {
        id: 'h-5',
        rowNumber: 5,
        activity: 'تعیین ضخامت ورق فولادی',
        potentialHazard: 'استنشاق دود و دمه و میست روغنی',
        consequence: 'نارسایی تنفسی، التهاب ریه، مسمومیت مزمن شغلی',
        rootCauses: 'دود و دمه ناشی از آب صابون صنعتی، دمای بالای فرآیند برش و چرخش رول‌ها، نقص در مکش هود',
        severity1: 7,
        occurrence1: 7,
        detection1: 3,
        rpn1: 147,
        judgment1: 'M',
        existingControls: 'هود موضعی با مکش کم، ماسک پارچه‌ای',
        proposedControls: 'تعمیر و نگهداری PM تهویه به صورت منظم انجام شود - تقویت فن سانتریفیوژ و نصب فیلتر الکترواستاتیک',
        correctiveAction: {
          id: 'ca-5',
          title: 'سرویس دوره‌ای PM ماهانه سیستم تهویه موضعی و تعویض فیلترهای روغنی',
          description: '۱. ثبت برنامه مدون PM در سیستم نگهداری جهت شستشوی کانال‌ها هر ۴۵ روز ۲. بالانس پروانه اگزاست فن و ارتقای موتور ۳. تامین ماسک‌های کربن اکتیو FFP2/FFP3 برای کارگران',
          responsiblePerson: '',
          department: 'واحد PM',
          targetDate: '1405/04/10',
          status: 'in_progress',
          estimatedCost: '۱۹,۵۰۰,۰۰۰ تومان',
          effectivenessReview: 'میزان دمه مرئی به صفر رسیده و راندمان مکش هود بالای ۹۰٪ اندازه گیری شده است.',
          isApprovedByHSE: true,
        },
        severity2: 5,
        occurrence2: 4,
        detection2: 3,
        rpn2: 60,
        judgment2: 'L',
        tags: ['شیمیایی', 'تهویه', 'بهداشت حرفه‌ای'],
        createdAt: '1404/07/15',
        updatedAt: '1404/07/25',
      },
    ],
  },
  {
    id: 'ws-press-kari-1404',
    workshopName: 'پرس‌کاری سنگین',
    executionDate: '1404/07/22',
    reviewPeriod: 'سه ماهه',
    teamMembers: ['محمد مونسان', 'سعید شفیعی', 'مهدی احمدی', 'مهندس مهدی نوری'],
    teamApproved: true,
    teamApprovedDate: '1404/07/23',
    hseManagerApproved: false,
    hseManagerName: 'حمید رفیعیان',
    status: 'under_review',
    notes: 'ارزیابی خطرات پرس ضربه‌ای و هیدرولیک ۲۰۰ تن قالب‌سازی',
    hazards: [
      {
        id: 'h-6',
        rowNumber: 1,
        activity: 'پرس و فرم‌دهی قطعات ضخیم',
        potentialHazard: 'له‌شدگی دست زیر سمبه و ماتریس پرس',
        consequence: 'قطع عضو دائم، شوک تروماتیک، فوت',
        rootCauses: 'بای‌پس کردن سیستم کنترل دو شستی توسط اپراتور، فقدان حفاظ اینترلاک مکانیکی',
        severity1: 10,
        occurrence1: 6,
        detection1: 4,
        rpn1: 240,
        judgment1: 'H',
        existingControls: 'کلید دو شستی معمولی بدون رله ضد چسبندگی',
        proposedControls: 'نصب سیستم ضد تکرار کورس (Anti-Repeat Relay)، پرده نوری حساس به دست و قفل درب فیزیکی',
        correctiveAction: {
          id: 'ca-6',
          title: 'طراحی مدار دو شستی همزمان غیرقابل بای‌پس و پرده نوری تیپ ۴',
          description: '۱. تعویض مدار الکتریکی به رله پیلز ایمنی استاندارد ۲. تست روزانه کالیبراسیو پرده نوری قبل از شروع کار ۳. صدور دستورالعمل ممنوعیت دستکاری سیستم ایمنی',
          responsiblePerson: '',
          department: 'تعمیرات و ایمنی',
          targetDate: '1405/02/15',
          status: 'pending',
          estimatedCost: '۳۴,۰۰۰,۰۰۰ تومان',
          effectivenessReview: 'در انتظار اجرای نهایی و تست ایمنی',
          isApprovedByHSE: false,
        },
        severity2: 7,
        occurrence2: 2,
        detection2: 4,
        rpn2: 56,
        judgment2: 'L',
        tags: ['پرس‌کاری', 'مکانیکی', 'ریسک بحرانی'],
        createdAt: '1404/07/22',
        updatedAt: '1404/07/22',
      },
      {
        id: 'h-7',
        rowNumber: 2,
        activity: 'تعویض قالب پرس سنگین',
        potentialHazard: 'سقوط قالب سنگین ۳ تنی حین جابجایی با جرثقیل سقفی',
        consequence: 'له‌شدگی، تخریب سازه، فوت',
        rootCauses: 'فرسودگی سیم بکسل، عدم بستن اشپیل قلاب، عدم استفاده از راهنمای طنابی',
        severity1: 9,
        occurrence1: 4,
        detection1: 5,
        rpn1: 180,
        judgment1: 'M',
        existingControls: 'بازرسی چشمی سالانه جرثقیل',
        proposedControls: 'تست غیرمخرب NDT قلاب، تعویض ماهانه سیم‌بکسل، آموزش ریگری به اپراتورها',
        correctiveAction: {
          id: 'ca-7',
          title: 'قرارداد تست هیدرواستاتیک و NDT ادواری با شرکت بازرسی مجاز',
          description: '۱. انجام تست بار و بازرسی ضخامت‌سنجی و ترک‌یابی قلاب ۲. اخذ گواهینامه معتبر ۶ ماهه ۳. نصب ضامن ایمنی تقویت‌شده روی تمام قلاب‌ها',
          responsiblePerson: '',
          department: 'واحد PM و ایمنی',
          targetDate: '1405/03/10',
          status: 'in_progress',
          estimatedCost: '۱۸,۰۰۰,۰۰۰ تومان',
          isApprovedByHSE: true,
        },
        severity2: 8,
        occurrence2: 2,
        detection2: 4,
        rpn2: 64,
        judgment2: 'L',
        tags: ['لیفتینگ', 'جرثقیل', 'سقوط بار'],
        createdAt: '1404/07/22',
        updatedAt: '1404/07/24',
      }
    ]
  }
];

export const INITIAL_ALERTS: HighRiskAlert[] = [
  {
    id: 'alt-1',
    hazardId: 'h-6',
    workshopName: 'پرس‌کاری سنگین',
    activity: 'پرس و فرم‌دهی قطعات ضخیم',
    hazardTitle: 'له‌شدگی دست زیر سمبه و ماتریس پرس (RPN: 240, شدت: ۱۰)',
    rpn: 240,
    severity: 10,
    judgment: 'H',
    triggeredAt: '1404/07/22 - 10:30',
    status: 'active',
    severityLevel: 'critical',
    recipientsNotified: ['حمید رفیعیان (مسئول ایمنی و بهداشت)', 'عادل مرادی (تعمیرات)', 'سعید شفیعی (افسر ایمنی)'],
    dispatchChannels: ['sms', 'email', 'in_app'],
    actionRequired: 'توقف فوری فعالیت در صورت عدم عملکرد سنسور دو شستی و اعزام افسر ایمنی جهت پلمپ یا اصلاح فوری مدار',
  },
  {
    id: 'alt-2',
    hazardId: 'h-1',
    workshopName: 'نوردسرد',
    activity: 'تعیین ضخامت ورق فولادی',
    hazardTitle: 'برخورد ورق به اپراتور (RPN: 200, شدت: ۱۰)',
    rpn: 200,
    severity: 10,
    judgment: 'M',
    triggeredAt: '1404/07/15 - 08:45',
    status: 'resolved',
    severityLevel: 'high',
    recipientsNotified: ['حمید رفیعیان', 'محمد مونسان', 'مهندس مهدی نوری'],
    dispatchChannels: ['in_app', 'sms'],
    actionRequired: 'ساخت اتاقک اپراتوری عایق و درایو کنترل سرعت رول‌گیر انجام و تایید شد.',
  },
  {
    id: 'alt-3',
    hazardId: 'h-7',
    workshopName: 'پرس‌کاری سنگین',
    activity: 'تعویض قالب پرس سنگین',
    hazardTitle: 'سقوط قالب سنگین حین جابجایی با جرثقیل (RPN: 180, شدت: ۹)',
    rpn: 180,
    severity: 9,
    judgment: 'M',
    triggeredAt: '1404/07/22 - 11:15',
    status: 'acknowledged',
    severityLevel: 'warning',
    recipientsNotified: ['مهندس مهدی نوری', 'سعید شفیعی', 'مهدی احمدی'],
    dispatchChannels: ['in_app'],
    actionRequired: 'بررسی ضامن قلاب و تکمیل بازرسی فنی ادواری ظرف ۱۰ روز آینده',
  }
];

export const INITIAL_PERIODIC_REPORTS: PeriodicReport[] = [
  {
    id: 'rep-fall-1404',
    title: 'گزارش ارزیابی جامع ریسک و اثربخشی CAPA فصل پاییز ۱۴۰۴',
    period: 'پاییز ۱۴۰۴ (مهر تا آذر)',
    workshopName: 'کلیه کارگاه‌ها (نورد سرد و پرس‌کاری)',
    createdAt: '1404/07/25',
    reporterName: 'حمید رفیعیان (مسئول واحد ایمنی و بهداشت)',
    totalHazards: 7,
    highRiskCount: 2,
    mediumRiskCount: 4,
    lowRiskCount: 1,
    averageRpnInitial: 167.3,
    averageRpnResidual: 74.5,
    riskReductionPercentage: 55.4,
    completedActionsCount: 4,
    pendingActionsCount: 3,
    complianceScore: 88,
    summaryText: 'با هماهنگی مسئول ایمنی و بهداشت (حمید رفیعیان)، افسران ایمنی (سعید شفیعی، محمد مونسان، مهدی احمدی) و همکاری مسئول PM (مهندس مهدی نوری) و مسئول تعمیرات (عادل مرادی)، اقدامات کنترلی مهندسی با موفقیت اجرا و ریسک‌ها به میزان ۵۵.۴ درصد کاهش یافت.',
    keyRecommendations: [
      'تجهیز پرس ۲۰۰ تن به رله ایمنی پیلز و پرده نوری توسط واحد تعمیرات (عادل مرادی) تا پایان آبان‌ماه',
      'برگزاری دوره بازآموزی ریگری و کار با جرثقیل‌های سقفی توسط افسران ایمنی برای کلیه شیفت‌ها',
      'پایش مستمر دزیمتری صدا و اندازه گیری عوامل شیمیایی در دی‌ماه ۱۴۰۴',
      'اجرای برنامه منظم سرویس PM سیستم تهویه نورد توسط واحد PM (مهندس مهدی نوری)'
    ]
  },
  {
    id: 'rep-summer-1404',
    title: 'گزارش سه ماهه دوم تابستان ۱۴۰۴ - پایش ریسک‌های عملیاتی',
    period: 'تابستان ۱۴۰۴ (تیر تا شهریور)',
    workshopName: 'کارگاه نوردسرد',
    createdAt: '1404/06/30',
    reporterName: 'سعید شفیعی (افسر ایمنی)',
    totalHazards: 5,
    highRiskCount: 2,
    mediumRiskCount: 2,
    lowRiskCount: 1,
    averageRpnInitial: 149.8,
    averageRpnResidual: 80.4,
    riskReductionPercentage: 46.3,
    completedActionsCount: 3,
    pendingActionsCount: 2,
    complianceScore: 78,
    summaryText: 'ممیزی‌های دوره‌ای نشان‌دهنده نیاز مبرم به اصلاح وضعیت لغزندگی کف کارگاه نورد و سنسور قطع‌کن گیوتین بود که اقدامات لازم تعریف شد.',
    keyRecommendations: [
      'اصلاح درین‌های روغن و آب‌صابون توسط واحد تعمیرات',
      'اجباری شدن استفاده از کفش‌های ایمنی تخصصی ضد لغزش SRC'
    ]
  }
];

export const WORKSHOP_LIST = [
  'نوردسرد',
  'پرس‌کاری سنگین',
  'تراشکاری و CNC',
  'ریخته‌گری و ذوب',
  'انبار مواد اولیه و شیمیایی',
  'خط بسته‌بندی و بارگیری',
];
